var business = 5000;
var minister = 7000;
var sochib = 1000;
var kBoro = Math.max(business, minister, sochib);
console.log(kBoro);
/**if(business>minister){
    if(business>sochib){
        console.log('business is bigger');
    }
    else{
        console.log('sochib is bigger');
    }
    if(minister>sochib){
        console.log('minister is bigger');
    }

}
else{
    console.log('sochib is bigger');
}*/
